name: CI and CD
on:
  push:
    branches:
      - Main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
#      - name: Set-up Node
#        uses: actions/setup-node@v1
#        with:
#          node-version: "14.17.*"
      - run: git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      - run: npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_REPO_TOKEN }}
        REACT_APP_API_KEY: ${{ secret.REACT_APP_API_KEY }}