name: CI

on:
  push:
    branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Build
        run: |
          npm install
          npm run-script build
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}

      - name: Deploy
        uses: NataPlato/memo
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
